services:
- mongodb
language: node_js
node_js:
- 0.10.35
  - "0.10"
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: $OPENSHIFT_APP
  domain: $OPENSHIFT_DOMAIN
  on:
    repo: quaz3l/rollerbakers
env:
  global:
  - secure: BcTtNnK+R3dhnZDQgJf2t7/Nayka3w02wiQPuHWCxGrZ5DF8DByluhL5xTvNoArFac9+akUgBW0uidzX6vK/znc0rP0e6/23mV3vxDlHk4+3UOB8R0iZENtvV3VH/UMGDnvA7aqQdhYgBGya8EjUnnq+cvb1VOfgMdLQVIu8aJFNmoEWrOm+PO4vkf73gT/I0HgGQM3pKwYe6aUeJ6W820MSxXGezrvpEdGG8flQ6taf/zxB2XtU2tbIn1uhAF/SVzVKIHP1N+4qOOO3rrMm/OwfOE+uFa33as0O4C7d/RvWiBGHBfBh2AYQ4w3jOm/ZjSTGJBbnN472l7ONpzOHFCWtHpepb/eAxzOYR4BYtaMqELTZefaYpcXDE09kT7ssAf2RGk9DoD/ZEFRQ5y6ZdafLdbARiYRgjVNYnvIpbXux3FMFFr/+HK+aEvfH2q0ly9osCcQExTIiIXCBOHSwauGsmQLGoklNHWa2ljkij2RwCNy1z0Nz081RCjO6MIcFWEfVM20Max2V6WQYEe7hYaDUFLpj4CyhwemGlwwVX+rDIjqezVk5tECiN/LOexmswrFVjmA1xpMY0pZyofrlh2UFEE9SpiFYmwLuTreP/FHZXihXfWAsA1cbPQmH5/1mmbzsC3swtRwz7W/00crMeZgVZBNQntrsdQ24LFxAZjQ=
  - secure: dJ2MGNYzPuRlznXis9E8XB1zu5OnwIPKcL5y1pBy3EC0ggTuw2Q+pzlhPHKtqtLamn6Qzu4PNuhRVFafWI0FwZYn0ifmDttn1gEavvpjsaq3XsMQJc9oFfwuwLYBgemauPursMft4YtgeNnVbVKKICofwM1CgZY3tBieq09IxmsMeENpecwnxdESgq6aej8BE21du+pK/BuutnTKdUVwV55gWEFmZLr8EYR/srM+kmVcKpYkomHrVlpqA8ISl8tb40l8kxeQKBYskn7538FKHQGUOBUI0iVTkrDimOibXyvP+W47wcyHNbsUzd7JtE1KWfkvxKY/GKTyoyK1+Y1FTUfA3nTJprU5DTbGr9lVs2MZGwI1vkm2Q3iB/IEIDV39ygI84hIJpM2TH7GrabzBQnadmuvHo5DsLlz6iZdfOhLx/bZhsk1cVJRVAPXufjRn4v/Xw9iO+qAzO/OLnvFDxp5Snt4yqI/8QbRMXBcBP0gp8skDlDFyI+qzhQhnqH3uavRgqJ0vLweRZ+JLxYdaMCdFMJ6TIPnLMtfhcSXQv7CGrU1KMUlpI4sSuZA2qJA9tRc3E6yg54qPUzM0UK8jS3ITP3pFKMYdBcyMfT4G0uIMBdu5cDNgZ5+vzWobvRzcpjnFmfA+ddGTWA4G2qBbT+dFgDiOIXUgl2SDHsEZq4Q=
  - secure: mA12YqXOJcN6Sz+p0lsDG+9t3dw6z7N9uL1Zh9i0OV7w2nV+04Pc3DYurOk9GnZI3awHf1gSl3go2kHlRSyGhG5pQiehrbPbPwGpP+57NHDvDuzA48nctrgSOcSgMkrotovMRymc6sn16Xc3v9ABYar34CVccMgSVvUlxh36cDAKVUNC73D9WheT8a1goyx8KCypy48kLJLqiksAyZm+FZjxP8UI/UnDSyPKcPiKPMk153xAnosnxbLgEn7rbL6KSkgU8K168cCjZiYYBYtzwrQIFvymg2A3ZdUiNvec5M+caxyvxrhjj9xe9yJzufCi1x+ukxaD/urVbaa2KaOdYUwAEAHOPBu1KVVvRxMeew8Y57Z8sFani0mAJf05j/ssv4UbPeI+tdlHB+pF1iqKWS5c2cy6AvNPZQzmpPyg1T7pquMlh6oe+pZh2b4frXBZgrX/mc0fzhhDKijQisizRP8xgdy6SHelqODlmZm1T0zxMjvJ1sI7FTqwDkqZeOjjxMhumtZwQZ/duYbeRcnVDo6WCo17dfIeH0tk9I04Cc9qYIodUk0oXdg8XGbjdcLAYGA7Q7SiNyttjUTo0lekTvyJcaefMqaWCCfMKofnyaeU21y18oayjFWOlzmN+GDQJIZT8Ys8SAKiu9YnY9dNkG8RMs44tnHJ0dl4nRmJ6cY=
before_script:
  - npm install expresso
after_success:
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git add --all
- git commit -am "Travis change"
